name: social_media
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  intl: ^0.18.0
  chewie: ^1.7.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  http: ^1.3.0
  shared_preferences: ^2.0.6
  camera: ^0.11.1
  firebase_messaging: ^14.7.10
  firebase_messaging_web: ^3.5.18
  flutter_local_notifications: ^17.0.0
  image_picker: ^0.8.5+3
  firebase_core: ^2.16.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # Add custom fonts if needed:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

